# -*- coding: utf-8 -*-
"""Aula3subLPC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MK-r1bihXMMQjRFcFF_HLh1UJZLzvB5Z
"""

# ETE Porto Digital
# Disciplina: LPC1
# Professor: Cloves
# Estudante: Guilherme F.


print("Hello, ETE Porto Digital")