# -*- coding: utf-8 -*-
"""ForStructure.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mY8ZPKFbNBrhmyzz3JEl7AlR6mlmHIg7
"""

pessoas = [] #Lista vazia.
idades = []
for p in range (0, 5):
  print('Pessoa: ', p+1)
  pessoa = input('Digite o nome da pessoa: ')
  pessoas.append(pessoa)
  print ('Idade: ', p+1)
  idade = input('Digite a idade da pessoa: ')
  idades.append(idade)
 # Imprimi a lista de pessoas cadastrada.
print(pessoas)
print(idades)

rank = sorted(idades, reverse = True)

print("Abaixo está o rank de idades")
print(rank)